name: 'Build and Deploy ML Project'
description: 'Build and deploy your Edge Impulse project'
author: 'Edge Impulse'
branding:
  icon: download
  color: green
inputs:
  project_id:
    description: 'Studio Project ID'
    required: true
    default: ''
  api_key:
    description: 'Studio Project API key'
    required: true
    default: ''
  impulse_id:
    description: 'Impulse ID'
    required: false
    default: ''
  engine:
    description: 'Engine type. Available options, see: https://docs.edgeimpulse.com/apis/studio/jobs/build-on-device-model#body-engine'
    required: true
    default: 'tflite-eon'
  deployment_type:
    description: 'Type of the deployment'
    required: false
    default: 'zip'
outputs:
  deployment_file_name:
    description: 'Name of the downloaded deployment file'
runs:
  using: 'node16'
  main: 'dist/index.js'
